// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP3_SoftwareEscalavel.Infrastructure.Persistence;

#nullable disable

namespace TP3_SoftwareEscalavel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TP3MicrosservicoDbContext))]
    partial class TP3MicrosservicoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Atividade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataFinalEntrega")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DataInicioEntrega")
                        .HasColumnType("Date");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.AtividadeAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataEntrega")
                        .HasColumnType("Date");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdAtividade")
                        .HasColumnType("int");

                    b.Property<decimal?>("Nota")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.HasIndex("IdAtividade", "IdAluno")
                        .IsUnique();

                    b.ToTable("AtividadeAlunos");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Chamada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("Date");

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataCriacao", "IdDisciplina", "IdAluno")
                        .IsUnique();

                    b.ToTable("Chamadas");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Disciplina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdProfessor")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProfessor");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.DisciplinaAluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdAluno")
                        .HasColumnType("int");

                    b.Property<int>("IdDisciplina")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAluno");

                    b.HasIndex("IdDisciplina", "IdAluno")
                        .IsUnique();

                    b.ToTable("DisciplinaAlunos");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Disciplina", b =>
                {
                    b.HasOne("TP3_SoftwareEscalavel.Core.Entities.Professor", "Professor")
                        .WithMany("Disciplinas")
                        .HasForeignKey("IdProfessor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.DisciplinaAluno", b =>
                {
                    b.HasOne("TP3_SoftwareEscalavel.Core.Entities.Disciplina", null)
                        .WithMany("Alunos")
                        .HasForeignKey("IdAluno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Disciplina", b =>
                {
                    b.Navigation("Alunos");
                });

            modelBuilder.Entity("TP3_SoftwareEscalavel.Core.Entities.Professor", b =>
                {
                    b.Navigation("Disciplinas");
                });
#pragma warning restore 612, 618
        }
    }
}
